# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Assignment1_pb2 as Assignment1__pb2


class TweetStub(object):
  """The tweet service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestTweets = channel.unary_stream(
        '/Tweet/RequestTweets',
        request_serializer=Assignment1__pb2.TweetRequest.SerializeToString,
        response_deserializer=Assignment1__pb2.TweetReply.FromString,
        )


class TweetServicer(object):
  """The tweet service definition.
  """

  def RequestTweets(self, request, context):
    """streams tweets
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestTweets': grpc.unary_stream_rpc_method_handler(
          servicer.RequestTweets,
          request_deserializer=Assignment1__pb2.TweetRequest.FromString,
          response_serializer=Assignment1__pb2.TweetReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Tweet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
