# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Assignment1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Assignment1.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x41ssignment1.proto\"(\n\x0cTweetRequest\x12\x18\n\x10number_of_tweets\x18\x01 \x01(\x05\"`\n\nTweetReply\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x0c\n\x04\x66lag\x18\x04 \x01(\t\x12\x0c\n\x04user\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\x06 \x01(\t28\n\x05Tweet\x12/\n\rRequestTweets\x12\r.TweetRequest\x1a\x0b.TweetReply\"\x00\x30\x01\x62\x06proto3'
)




_TWEETREQUEST = _descriptor.Descriptor(
  name='TweetRequest',
  full_name='TweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_tweets', full_name='TweetRequest.number_of_tweets', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=61,
)


_TWEETREPLY = _descriptor.Descriptor(
  name='TweetReply',
  full_name='TweetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='TweetReply.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='TweetReply.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='TweetReply.date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='TweetReply.flag', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='TweetReply.user', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='TweetReply.text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['TweetRequest'] = _TWEETREQUEST
DESCRIPTOR.message_types_by_name['TweetReply'] = _TWEETREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TweetRequest = _reflection.GeneratedProtocolMessageType('TweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _TWEETREQUEST,
  '__module__' : 'Assignment1_pb2'
  # @@protoc_insertion_point(class_scope:TweetRequest)
  })
_sym_db.RegisterMessage(TweetRequest)

TweetReply = _reflection.GeneratedProtocolMessageType('TweetReply', (_message.Message,), {
  'DESCRIPTOR' : _TWEETREPLY,
  '__module__' : 'Assignment1_pb2'
  # @@protoc_insertion_point(class_scope:TweetReply)
  })
_sym_db.RegisterMessage(TweetReply)



_TWEET = _descriptor.ServiceDescriptor(
  name='Tweet',
  full_name='Tweet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=161,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestTweets',
    full_name='Tweet.RequestTweets',
    index=0,
    containing_service=None,
    input_type=_TWEETREQUEST,
    output_type=_TWEETREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWEET)

DESCRIPTOR.services_by_name['Tweet'] = _TWEET

# @@protoc_insertion_point(module_scope)
