# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Assignment1_pb2 as Assignment1__pb2


class TweetStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestATweet = channel.unary_unary(
        '/helloworld.Tweet/RequestATweet',
        request_serializer=Assignment1__pb2.TweetRequest.SerializeToString,
        response_deserializer=Assignment1__pb2.TweetReply.FromString,
        )


class TweetServicer(object):
  """The greeting service definition.
  """

  def RequestATweet(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestATweet': grpc.unary_unary_rpc_method_handler(
          servicer.RequestATweet,
          request_deserializer=Assignment1__pb2.TweetRequest.FromString,
          response_serializer=Assignment1__pb2.TweetReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Tweet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
